group: travis_latest
language: python
cache: pip
python:
  - 3.5
install:
  - pip install --upgrade pip
  - pip install -r requirements.test.txt
  - pip install flake8
  - pip install -U pytest
  - pip install -U codecov
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest # add other tests here
after_success:
  - codecov # submit coverage
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
